name: pull request testing workflow

on:
  pull_request:
    branches: ["dev", "master", "devQA", "releaseQA"]

jobs:
  test:
    runs-on: [self-hosted, crow]
    steps:
    - name: Checkout to branch ${{ github.action_ref }}
      uses: actions/checkout@v4
    
    - name: Run tests with torch 2.1 + cuda12.1
      run: docker run --rm -v /home/owlite/crow-repo/owlite-develop/owlite-develop:/workspace -v /home/owlite/crow-cache:/root/.cache -e TORCHVISION_VERSION=0.16.0 -e TRANSFORMERS_VERSION=4.32 pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel /bin/bash /workspace/.github/workflows/pipeline.sh
      
    - name: Run tests with torch 2.2 + cuda12.1
      run: docker run --rm -v /home/owlite/crow-repo/owlite-develop/owlite-develop:/workspace -v /home/owlite/crow-cache:/root/.cache -e TORCHVISION_VERSION=0.17.0 -e TRANSFORMERS_VERSION=4.38 pytorch/pytorch:2.2.1-cuda12.1-cudnn8-devel /bin/bash /workspace/.github/workflows/pipeline.sh
